apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          env:
            - name: NEXT_PUBLIC_DB_HOST
              value: "172.16.98.151"
            - name: NEXT_PUBLIC_DB_PORT
              value: "5432"
            - name: NEXT_PUBLIC_PREFIX_DB_NAME_WITH_USERNAME
              value: "yes"
            - name: NEXT_PUBLIC_HELP_URL
              value: "https://jtektjp.sharepoint.com/sites/ja_0090/SitePages/Self-service-DB%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9.aspx?web=1"
          envFrom:
            - secretRef:
                name: env-secret
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 3000
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
